user-access-management:
  mail-mq:
    queue-name: mail-queue
  jwt:
    issuer: user-access-management
    valid-minutes: 60
  clients:
    service-y:
      client-id: service-y
      private-key-path: src/main/resources/private_key.pem
      public-key-path: src/main/resources/public_key.pem
    service-z:
      client-id: service-z
      private-key-path: src/main/resources/private_key.pem
      public-key-path: src/main/resources/public_key.pem

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/user-access-management-db
    driverClassName: org.postgresql.Driver
    username: postgres
    password: postgres

  jpa:
    hibernate:
      ddl-auto: validate

  flyway:
    enabled: true
    locations: classpath:db/migration/ddl,classpath:db/migration/data
    baselineOnMigrate: true