user-access-management:
  verification-url: http://localhost:8080/auth/confirm-email?token={token}
  password-reset-url: http://localhost:8080/auth/reset-password?token={token}
  mail-mq:
    queue-name: mail-queue
  jwt:
    issuer: user-access-management
    valid-minutes: 60
  security:
    cors:
      allowed-origins:
        - http://localhost:4200

server:
  port: 8090

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/user-access-management-db
    driverClassName: org.postgresql.Driver
    username: postgres
    password: postgres

  jpa:
    hibernate:
      ddl-auto: validate

  flyway:
    enabled: true
    locations: classpath:db/migration/ddl,classpath:db/migration/data
    baselineOnMigrate: true
  rabbitmq:
    host: localhost
    port: 2008
    username: guest
    password: guest
    virtual-host: /